# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Tue Nov 11 10:56:34 CET 2025

---
apiVersion: xl-release/v1
kind: Applications
metadata:
  path: /
  home: S-125620
spec:
- name: T1
  type: xlrelease.Application
